name: Actions

on:
  issues:
    types: opened
  issue_comment:

jobs:
  process:
    name: Process
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process Label Action
        uses: rtm516/GeyserMC-actions/issues-dump@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
